### PR TITLE
Validation

### PR DESCRIPTION
**Pull request by awaisanwar544**
Add validation for
1. User Model
2. Post Model

Add Tests for
1. user
2. post
3. like
4. comment

Screenshot 2022-06-11 at 7 57 15 PM

### CODE REVIEW

**Review by keneogu — CHANGES_REQUESTED** [review]
Hi @awaisanwar544, 

Good job so far!

- All linters are passing
- You are following GitHub flow
- Good commit history
- Good PR description

There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [x] Your code should be able to solve the `N+1` problem. Example: The post#index action should use `@posts = @user.posts.includes(:comments) instead of @posts = @user.posts`

- [x] Your root 'users#index' route doesn't display on the screen. I can only see a blank screen.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by awaisanwar544** [comment]
@keneogu Can you please refer to where did you find this `@posts = @user.posts`
because post#index action already includes `@posts = Post.includes(:comments, comments: [:user]).where(user_id: user_index).order(id: :desc)`

**Comment by awaisanwar544** [comment]
Also `users#index` route is working fine in my case

Screenshot 2022-06-11 at 11 07 05 PM
Screenshot 2022-06-11 at 11 06 53 PM

**Review by DeliceLydia — APPROVED** [review]
## Hi @awaisanwar544, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
